Make Python output unbuffered (fixes CI output)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -75,7 +75,7 @@ jobs:
         run: "[[ -d ${{ env.LTEX_LS_IDEA_DIRECTORY_NAME }} ]] || { wget https://download.jetbrains.com/idea/${{ env.LTEX_LS_IDEA_ARCHIVE_NAME }} && tar -xzf ${{ env.LTEX_LS_IDEA_ARCHIVE_NAME }}; }"
 
       - name: "Inspect Code with IntelliJ IDEA"
-        run: "python tools/inspectWithIntellijIdea.py --idea-path ${{ env.LTEX_LS_IDEA_DIRECTORY_NAME }}"
+        run: "python -u tools/inspectWithIntellijIdea.py --idea-path ${{ env.LTEX_LS_IDEA_DIRECTORY_NAME }}"
 
   validate:
     name: "CI - Validate Job"
@@ -91,16 +91,16 @@ jobs:
           python-version: "3.9.0"
 
       - name: "Install Python Dependencies"
-        run: "python -m pip install --upgrade pip && pip install xmlschema==1.6.4"
+        run: "python -u -m pip install --upgrade pip && pip install xmlschema==1.6.4"
 
       - name: "Validate .assembly.xml"
-        run: "python -c 'import xmlschema; xmlschema.XMLSchema(\"schemas/assembly-2.1.0.xsd\").validate(\".assembly.xml\")'"
+        run: "python -u -c 'import xmlschema; xmlschema.XMLSchema(\"schemas/assembly-2.1.0.xsd\").validate(\".assembly.xml\")'"
 
       - name: "Validate changelog.xml"
-        run: "python -c 'import xmlschema; xmlschema.XMLSchema(\"schemas/changes-1.0.0.xsd\").validate(\"changelog.xml\")'"
+        run: "python -u -c 'import xmlschema; xmlschema.XMLSchema(\"schemas/changes-1.0.0.xsd\").validate(\"changelog.xml\")'"
 
       - name: "Validate pom.xml"
-        run: "python -c 'import xmlschema; xmlschema.XMLSchema(\"schemas/maven-4.0.0.xsd\").validate(\"pom.xml\")'"
+        run: "python -u -c 'import xmlschema; xmlschema.XMLSchema(\"schemas/maven-4.0.0.xsd\").validate(\"pom.xml\")'"
 
   upload_coverage:
     name: "CI - Upload Coverage Job"
@@ -149,22 +149,22 @@ jobs:
           python-version: "3.9.0"
 
       - name: "Install Python Dependencies"
-        run: "python -m pip install --upgrade pip && pip install semver==2.13.0"
+        run: "python -u -m pip install --upgrade pip && pip install semver==2.13.0"
 
       - name: "Set LTEX_LS_VERSION"
-        run: "echo \"LTEX_LS_VERSION=$(python -c \"import re; print(re.search(r'<version>(.*?)</version>', open('pom.xml', 'r').read()).group(1), end='')\")\" >> $GITHUB_ENV"
+        run: "echo \"LTEX_LS_VERSION=$(python -u -c \"import re; print(re.search(r'<version>(.*?)</version>', open('pom.xml', 'r').read()).group(1), end='')\")\" >> $GITHUB_ENV"
 
       - name: "Check LTEX_LS_VERSION"
         run: "if [[ -z \"$LTEX_LS_VERSION\" ]]; then echo 'Error: LTEX_LS_VERSION not set!'; (exit 1); fi; echo \"LTEX_LS_VERSION set to '$LTEX_LS_VERSION'\""
 
       - name: "Set LTEX_LS_IS_PRERELEASE"
-        run: "if [[ -z \"$LTEX_LS_VERSION\" ]]; then echo 'Error: LTEX_LS_VERSION not set!'; (exit 1); fi; echo \"LTEX_LS_IS_PRERELEASE=$(python -c \"import semver; print('true' if semver.VersionInfo.parse('$LTEX_LS_VERSION').prerelease is not None else 'false', end='')\")\" >> $GITHUB_ENV"
+        run: "if [[ -z \"$LTEX_LS_VERSION\" ]]; then echo 'Error: LTEX_LS_VERSION not set!'; (exit 1); fi; echo \"LTEX_LS_IS_PRERELEASE=$(python -u -c \"import semver; print('true' if semver.VersionInfo.parse('$LTEX_LS_VERSION').prerelease is not None else 'false', end='')\")\" >> $GITHUB_ENV"
 
       - name: "Check LTEX_LS_IS_PRERELEASE"
         run: "if [[ -z \"$LTEX_LS_IS_PRERELEASE\" ]]; then echo 'Error: LTEX_LS_IS_PRERELEASE not set!'; (exit 1); fi; echo \"LTEX_LS_IS_PRERELEASE set to '$LTEX_LS_IS_PRERELEASE'\""
 
       - name: "Set LTEX_LS_CHANGELOG"
-        run: "if [ \"$LTEX_LS_IS_PRERELEASE\" = \"false\" ]; then echo \"LTEX_LS_CHANGELOG<<EOF\" >> $GITHUB_ENV; python tools/convertChangelog.py --xml-file changelog.xml --version latest >> $GITHUB_ENV; echo \"EOF\" >> $GITHUB_ENV; else echo \"LTEX_LS_CHANGELOG=This is a pre-release. Use at your own risk.\" >> $GITHUB_ENV; fi"
+        run: "if [ \"$LTEX_LS_IS_PRERELEASE\" = \"false\" ]; then echo \"LTEX_LS_CHANGELOG<<EOF\" >> $GITHUB_ENV; python -u tools/convertChangelog.py --xml-file changelog.xml --version latest >> $GITHUB_ENV; echo \"EOF\" >> $GITHUB_ENV; else echo \"LTEX_LS_CHANGELOG=This is a pre-release. Use at your own risk.\" >> $GITHUB_ENV; fi"
 
       - name: "Build LTeX LS"
         run: "mvn -B -e package"
